LANGUAGES = [
    {"code": "en", "name": "English", "voice": "en-IN"},
    {"code": "hi", "name": "Hindi", "native": "हिन्दी", "voice": "hi-IN"},
    {"code": "te", "name": "Telugu", "native": "తెలుగు", "voice": "te-IN"},
    {"code": "ta", "name": "Tamil", "native": "தமிழ்", "voice": "ta-IN"},
    {"code": "mr", "name": "Marathi", "native": "मराठी", "voice": "mr-IN"},
    {"code": "bn", "name": "Bengali", "native": "বাংলা", "voice": "bn-IN"},
    {"code": "gu", "name": "Gujarati", "native": "ગુજરાતી", "voice": "gu-IN"},
    {"code": "kn", "name": "Kannada", "native": "ಕನ್ನಡ", "voice": "kn-IN"},
    {"code": "ml", "name": "Malayalam", "native": "മലയാളം", "voice": "ml-IN"},
    {"code": "pa", "name": "Punjabi", "native": "ਪੰਜਾਬੀ", "voice": "pa-IN"},
    {"code": "or", "name": "Odia", "native": "ଓଡ଼ିଆ", "voice": "or-IN"},
]

STATES = [
    "All India",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Delhi",
    "Jammu & Kashmir",
    "Ladakh",
    "Puducherry",
    "Chandigarh",
    "Other",
]

CATEGORIES = [
    "Agriculture",
    "Education",
    "Healthcare",
    "Employment",
    "Technology",
    "Infrastructure",
    "Environment",
    "Climate",
    "Smart Cities",
    "Rural Development",
    "Women Empowerment",
    "Entrepreneurship",
    "Digital India",
    "Manufacturing",
    "Transportation",
    "Energy",
    "Space & Science",
]

